# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_thumbsdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbsdown',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='thumbsdown',
            name='user',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='visitors',
        ),
        migrations.DeleteModel(
            name='ThumbsDown',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
