# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20161222_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(null=True, upload_to='restaurant-images'),
        ),
    ]
