# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0005_auto_20161221_1641'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LunchProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbsdowns', models.ManyToManyField(related_name='thumbsdown_users', to='restaurants.Restaurant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visits', models.ManyToManyField(related_name='visitors', to='restaurants.Restaurant')),
            ],
        ),
    ]
