# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lunchprofile_can_create_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars'),
        ),
    ]
