# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20161220_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_avatar_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='user_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
